[package]
name = "wvm"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
ureq = { version = "2.9.7", features = ["default", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"